### ISSUE TITLE
thread 'main' panicked at gossip-bin/src/ui/wizard/setup_relays.rs:144:25:

### ISSUE THREAD

**Issue by ufm** [mikedilger/gossip#551] opened 2023-10-16 02:19 UTC
thread 'main' panicked at gossip-bin/src/ui/wizard/setup_relays.rs:144:25:
not implemented
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:117:5
   3: core::ops::function::FnOnce::call_once{{vtable.shim}}
   4: egui::ui::Ui::allocate_ui_with_layout_dyn
   5: core::ops::function::FnOnce::call_once{{vtable.shim}}
   6: egui::ui::Ui::with_layout_dyn
   7: core::ops::function::FnOnce::call_once{{vtable.shim}}
   8: egui::ui::Ui::allocate_ui_with_layout_dyn
   9: gossip::ui::wizard::setup_relays::update
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
  12: egui::containers::frame::Frame::show_dyn
  13: egui::containers::panel::CentralPanel::show_dyn
  14: gossip::ui::wizard::update
  15: <gossip::ui::GossipUi as eframe::epi::App>::update
  16: eframe::native::epi_integration::EpiIntegration::update
  17: <eframe::native::run::glow_integration::GlowWinitApp as eframe::native::run::WinitApp>::run_ui_and_paint
  18: eframe::native::run::run_and_return::{{closure}}
  19: winit::platform_impl::platform::x11::EventLoop<T>::run_return::single_iteration
  20: winit::platform_impl::platform::x11::EventLoop<T>::run_return
  21: eframe::native::run::with_event_loop
  22: eframe::native::run::glow_integration::run_glow
  23: eframe::run_native
  24: gossip::ui::run
  25: gossip::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2023-10-16T02:17:20.536198Z  WARN /home/ufm/.cargo/git/checkouts/egui-8c292eaa01d4c64e/50393e4/crates/egui_glow/src/painter.rs:714: You forgot to call destroy() on the egui glow painter. Resources will leak!

**Comment by bu5hm4nn** [comment] 2023-10-16 18:36
Hey @ufm. What version were you running? From git (which branch?) or 0.8.1 release?

**Comment by ufm** [comment] 2023-10-16 23:48
> Hey @ufm. What version were you running? From git (which branch?) or 0.8.1 release?

From git, master branch.

**Comment by mikedilger** [comment] 2023-10-18 00:02
Must be one of the `.unwrap()` calls in `gossip-bin/src/ui/wizard/setup_relays.rs`

But after looking through them, the only situations where they would panic is if there was a catastrophic inability to read from LMDB, or if we hard-coded invalid relay URLs.  But my eyes are tired.  Anyone else see the problem?

**Comment by ufm** [comment] 2023-10-18 01:02
I don't use Gossip (and Nostr) on a regular basis, so I don't remember exactly what I did during the last Gossip launch. After the latest Gossip update, it started in wizard mode. Currently, at the "Setup Relays" step, my OUTBOX is empty, my INBOX is empty, and there are several entries in DISCOVERY. When attempting to delete even one entry (initially, I wanted to remove all servers from all lists) from DISCOVERY, this error occurs.

**Comment by mikedilger** [comment] 2023-10-18 04:12
Thanks. I can reproduce now.

**Comment by mikedilger** [comment] 2023-10-18 04:18
Ok I can fix the crash easily, there was a code block that had `unimplemented!()` which panics.

But it is a bit trickier to suggest purplepag.es to new users and allow it to be deleted because I can't easily tell apart the situation when you deleted it from the situation when you came in fresh so it just re-adds it. So it might be a bit longer to fix.

**Comment by mikedilger** [comment] 2023-10-18 04:29
I pushed a fix to unstable. I don't have time to test it thoroughly right now.  You can either try unstable, or you can just skip that wizard page and setup relays later.

**Comment by ufm** [comment] 2023-10-21 21:26
In the fresh master look like been fixed.

**Closed** 2023-10-22 07:09 UTC
