### ISSUE TITLE
Gossip freezes, can't initialize again after that

### ISSUE THREAD

**Issue by fiatjaf** [mikedilger/gossip#184] opened 2023-02-01 11:35 UTC
I was browsing some notes when suddenly the UI froze. These were the logs at the time:
![2023-02-01-083122_956x882_scrot](https://user-images.githubusercontent.com/1653275/216031244-901e4340-8c65-432d-9197-e4c486cbcad3.png)

I've closed it and started again, but it never goes beyond this phase now:
![2023-02-01-083106_953x191_scrot](https://user-images.githubusercontent.com/1653275/216031253-bef245e7-4755-4bd0-83ef-09bde1c08bdd.png)

Although the UI loads and I can click to setup my private key, browse to Relays, You, Settings, Help, Back and Feed (the feed doesn't show, tells me to setup my identity). If I click on People the UI freezes.

I tried to restart it multiple times and waited multiple minutes.

**Comment by mikedilger** [comment] 2023-02-01 18:10
Sorry about this.

For the moment, I brought master back to a stable commit and then applied pretty-safe patches to it.  Yes, it is another force-push, was too messy otherwise.   The previous master is preserved as the 'future' branch which I will try to debug when I have time (I don't have time right now).

**Comment by mikedilger** [comment] 2023-02-01 18:18
If gossip is still stuck even on this new force-pushed master, let me know.

**Comment by pjv** [comment] 2023-02-01 19:03
@mikedilger Still seems to be broken for me. I nuked the repo and re-cloned, rebuilt gossip, started it up and entered just my public key and it’s still beachballing me right after i import that key.

tried a few other things like starting again with a blank DB but it seems to choke as soon as it connects to the first relay (tried starting with two different relays to make sure it wasn’t the relay itself).

Here’s the log up until it freezes:

````
➜ ./target/release/gossip
 INFO Upgrading database to version 1
 INFO Upgrading database to version 2
 INFO Upgrading database to version 3
 INFO Upgrading database to version 4
 INFO Upgrading database to version 5
 INFO Upgrading database to version 6
 INFO Upgrading database to version 7
 INFO Upgrading database to version 8
 INFO Upgrading database to version 9
 INFO Upgrading database to version 10
 INFO Upgrading database to version 11
 INFO Upgrading database to version 12
 INFO Upgrading database to version 13
 INFO Upgrading database to version 14
 INFO Upgrading database to version 15
 INFO Upgrading database to version 16
 INFO Upgrading database to version 17
 INFO Upgrading database to version 18
 INFO Upgrading database to version 19
 INFO Upgrading database to version 20
 INFO Database is at version 20
 INFO Loaded 0 reply related events from the database
 INFO Loaded 0 feed related events from the database
 INFO Listening on 0 relays
 INFO Setup 1 relay for 0c99877612291bd818b3dd92f2852b823557b3744c3cb10470865c7a56a4929b
 INFO wss://relay.snort.social: Relay Information: Name="Snort Relay" Description="decent nostr relay" Pubkey="63fe6318dc58583cfe16810f86dd09e18bfd76aabc24a0081ce2856f330504ed" Contact="nostr@v0l.io" NIPS=[1, 2, 9, 11, 12, 15, 16, 20, 22, 26] Software="https://github.com/v0l/nostr-rs-relay" Version="0.7.13" id=""wss://relay.snort.social/""
 INFO wss://relay.snort.social: Connected
````

**Comment by mikedilger** [comment] 2023-02-01 19:15
I cannot reproduce. I just bootstraped from no database. It's pulling in lots of TextNotes and Reactions (damn default setting!)

I guess I'll just look through the newest commits that lock things and try to figure out where perhaps a deadlock might be occurring (presuming that is what is happening).

**Comment by mikedilger** [comment] 2023-02-01 19:32
Does 517a8bdcabc4341782d9e1ed27686d16bdfaabaa work still?

I"m afraid it might bitch about your database version though... if so you can rollback with:
````
ALTER TABLE person DROP COLUMN contact_list_last_received;
update settings set value=18 where key='version';
````
(schema 19 is idempotent so we don't have to roll it back)

**Comment by mikedilger** [comment] 2023-02-01 19:36
Ok the UI just froze for me after I tried to refresh metadata.

**Comment by pjv** [comment] 2023-02-01 19:36
@mikedilger not a rust guy - do i have to do anything to clean the old build artifacts after i check out 517a8bdc?

**Comment by mikedilger** [comment] 2023-02-01 19:39
@pjv I've never had to.

**Comment by pjv** [comment] 2023-02-01 19:41
awesome, i’ll wait then.

**Comment by mikedilger** [comment] 2023-02-01 19:48
Ok fixed on master.  Please verify.

I will restore all the other new code shortly too, after this fix is verified.

**Comment by pjv** [comment] 2023-02-01 19:50
Up and running. 🎆

**Comment by mikedilger** [comment] 2023-02-01 19:54
Ok, now for the slightly riskier part.  I put the fix on the future branch and moved master back over to future.  Can you try master again now @pjv or @fiatjaf?

**Comment by pjv** [comment] 2023-02-01 20:00
Seems to be running ok for me now on 3b2a650.

**Comment by mikedilger** [comment] 2023-02-01 20:19
Sweet.

**Closed by mikedilger** 2023-02-01 20:19 UTC
