### ISSUE TITLE
Replacing a key is broken

### ISSUE THREAD

**Issue by fiatjaf** [mikedilger/gossip#124] opened 2023-01-08 01:17 UTC
If I go on `YOU > Delete identity` I can delete my key. I don't lose my follow list. Then I can add a new key and use that.
Once I restart Gossip, though, the old key is back.

**Comment by mikedilger** [comment] 2023-01-08 01:45
Ok. Just to help me debug, were you adding private or public key? I recently added the ability to add just a public key, and it stores it separately from the private key, and if you have a private key it uses that to get the public key instead, so there may be something going on related to that.

**Comment by fiatjaf** [comment] 2023-01-08 01:58
I had a private key and added a new private key. I am pretty sire I had done this same thing 3 days ago and they previous key had also returned.

**Comment by mikedilger** [comment] 2023-01-08 06:36
Ok I've tried a number of combinations and I can't seem to reproduce this.

If you can reproduce it and explain precisely how, then I can reproduce it and then I can debug it.

The code looks right. On import or generate it save through the settings to the database and I've verified this on all the codepaths. I imported. I generated. I deleted. I tried combos on one session, or closing and reopening. I couldn't seem to break anything.

Maybe if you copy sqlite files around while it is running (I'm just grasping at straws now)

**Comment by fiatjaf** [comment] 2023-01-08 13:59
OK, I've just updated to `master` 5813237e0b8bb182aa6e7ca321d9526ce476f622 and deleted my directory `.local/share/gossip` and started Gossip.

Added my private key with `nsec`, added some follows, made a post, then restarted. My follows are there, my key is not.

I can't find a place for the key to be stored in the SQLite database, where is it supposed to be stored?

**Comment by fiatjaf** [comment] 2023-01-08 20:12
OK, now I am trying again and my key is here.

**Comment by mikedilger** [comment] 2023-01-22 00:38
In case this comes back or continues, the keys are stored in the settings table:  'public_key' and 'encrypted_private_key'.  I haven't seen this happen since and since there hasn't been activity on this issue recently I'm going to assume it's okay.  But please reopen if not.

**Closed by mikedilger** 2023-01-22 00:38 UTC
Labels: bug
